### ISSUE TITLE
Geen actie wanneer klant wilt bestellen met Bancontact

### ISSUE THREAD

**Issue by thierrymaasdam** [paynl/opencart-plugin#1]
Wanneer de klant na het kiezen van betaalmethode e.d. op "Bevestig Bestelling" drukt, gebeurt er niks, wanneer de methode Mistercash/Bancontact is gekozen. Ideal doet het overigens wel.

**Comment by andypieters** [comment]
Zou je hierover een mail kunnen sturen naar support@pay.nl?

Dan pakken we het van daaruit op.

Met vriendelijke groet,

Andy Pieters

**Comment by thierrymaasdam** [comment]
Beste,

Bij deze zou ik graag melding willen maken van een mogelijke bug in de OpenCart 2.0 plug-in. 

Op onze webshop hebben wij sinds kort ook MisterCash/Bancontact geactiveerd. Helaas hebben wij moeten constateren dat er niet wordt doorgestuurd naar de payment gateway nadat de 'klant' op de knop drukt om de bestelling te bevestigen. Betalen met andere betaalmethodes als iDeal en PayPal zijn doen het wel.

Misschien een suggestie hoe dit te verhelpen is? Of ligt het probleem in de plugin?

Groeten, 
Thierry Maasdam

Verstuurd vanaf mijn iPad.
